# version: "3.9"
# services:
#   postgres:
#     image: postgres:latest
#     container_name: betbot-postgres-db
#     environment:
#       POSTGRES_PASSWORD: "admin"
#       POSTGRES_USER: "postgres"
#       POSTGRES_DB: "bet_bot_go"
#     ports:
#       - "5432:5432"
#     restart: always
#   app:
#     build: BetBotGo
#     depends_on:
#       - postgres
#     ports:
#       - "8000:8080"
#     environment:
#       DATABASE_HOST: postgres
#     links:
#       - postgres
